fixed

diff --git a/.github/workflows/build-and-delivery.yml b/.github/workflows/build-and-delivery.yml
--- a/.github/workflows/build-and-delivery.yml
+++ b/.github/workflows/build-and-delivery.yml
@@ -18,6 +18,14 @@ jobs:
         with:
           fetch-depth: 0 # Если нужна полная история коммитов
 
+      - name: Verify Dockerfile exists
+        run: |
+          ls -la
+          if [ ! -f "Dockerfile" ]; then
+            echo "Dockerfile not found in root directory!"
+            exit 1
+          fi
+
       - name: Login to Docker Hub
         uses: docker/login-action@v3
         with:
